export const USER_REQUEST = "USER_REQUEST"
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS"
export const USER_REQUEST_FAIL = "USER_REQUEST_FAIL"



export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_REQUEST_SUCCESS = "USER_SIGNIN_REQUEST_SUCCESS"
export const USER_SIGNIN_REQUEST_FAIL = "USER_SIGNIN_REQUEST_FAIL"

export const USER_LOGOUT = "USER_LOGOUT"